### ISSUE TITLE
Silvia [mid-project-classification]

### ISSUE THREAD

**Issue by silviagonzalez98** [Ironhack-Data-0621-Remote/mid-bootcamp-project#13]
https://github.com/silviagonzalez98/Mid-Bootcamp-Project-Classification

**Comment by fromeropablo** [comment]
# Mid-Bootcamp-Project

Hello Silvia! Let's gonna check your mid-bootcamp project!!

### 1. ReadME and Repo Structure

First of all, great READMe! You have explained how your project is developing and what steps are you taking every time, that's really cool! The structured it's great and adding some plots and images give readers a better vision and, obviously, more interest on what you are doing.

Just a few details:

- Great work creating tables for the variables in the dataset! However, the **values* column doesn't add any important information about the variable itself. Instead, you can add a column with the meaning of each variable, it will give readers valuable info about they're gonna look at your project. 

- Good work showing the Python modules that you used for your project but you can do it in a prettier way:
```markdown
[Pandas](https://pandas.pydata.org/docs/)
```

Great work at all in this part, congrats!

### 2. SQL

Okay, so now it's time to check your SQL exercise. The set of questions is very complete and it was added to reinforce your knowledge of such an important skill as it is manage structured databases. 

Great work in this part, you have answered in such a great way, congrats!

### 3. Cleaning, processing and modeling your data

During this part you had to deal with cleaning and preprocessing techniques that you have been learning during the course many times. 

Great work at the beginning loading your database from SQL, congrats!!

Absolutely perfect job checking for distributions, outliers... using cool plots!! At all, your preprocessing and cleaning work is really good!

Just a few details:

- Remember to create a .py file to add your functions and call them in the jupyter. It's prettier and it will save you a lot of lines in your jupyter. 

- I missed explanation about the treatment of your data, the development of your work, explaining every step that you take. 

- Great that you used LogisticRegression and KNN models, but it would have been really cool if you would have tried some more. 

- At the end of your jupyter I missed a conclusion about the results and some insights that you already included in your ReadME. Take in mind that in your jupyter you have to extend the explanation that you gave in your presentation. 

Great job overall! I think that you already know but some things that you have to improve requires just some extra time so keep working in the same way and you will do a great final project for sure!
